# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Item')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=200)),
            ],
            bases=('catalogue.item',),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Item')),
                ('title', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=200)),
            ],
            bases=('catalogue.item',),
        ),
        migrations.AddField(
            model_name='quantity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Item'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Store'),
        ),
    ]
