# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='other_data',
        ),
        migrations.AlterField(
            model_name='book',
            name='id_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
